combine_control_expr = true
comment_width = 72
condense_wildcard_suffixes = true
edition = "2024"
style_edition = "2024"
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
max_width = 100
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
tab_spaces = 4
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
